const landingOverrides = {
  en: {
    meta_title: "TrueLock — Trust Capsules",
    meta_description: "Lock information by time, place, or password. Prove it existed before events.",
    logo_alt: "TrueLock logo",
    nav_pain: "Problem",
    nav_breakthrough: "Breakthrough",
    nav_cases: "Use cases",
    nav_security: "Security",
    nav_pricing: "Pricing",
    nav_download: "Download",
    cta_primary: "Create a Capsule",
    cta_secondary: "See how it works",
    hero_eyebrow: "Proof before the event",
    hero_title: "TrueLock — Trust Capsules for the real world",
    hero_subtitle_html: "Lock information by <strong>time</strong>, <strong>place</strong>, or <strong>password</strong>. Prove it existed before events.",
    hero_note: "No accounts. Works offline. Decrypt and verify are free.",
    hero_card_1_title: "Create",
    hero_card_1_desc: "Add text, files, photos, or video.",
    hero_card_2_title: "Lock",
    hero_card_2_desc: "Set rules: time, location, password, AND/OR.",
    hero_card_3_title: "Share",
    hero_card_3_desc: "Send the capsule anywhere. Open for free.",
    pain_title: "The internet is full of claims. But there is no proof.",
    pain_subtitle: "Every day:",
    pain_list_1: "Traders fake winning signals",
    pain_list_2: "Tipsters edit predictions after games",
    pain_list_3: "Influencers promise exclusive drops",
    pain_list_4: "Marketers run \"real\" campaigns",
    pain_list_5: "Journalists can't prove who knew what and when",
    pain_statement_title: "The same problem everywhere: anyone can change the past.",
    pain_statement_text: "Screenshots, posts, PDFs, documents — all can be edited, deleted, or forged.",
    pain_proof_title: "There is no way to prove:",
    pain_proof_1: "what was written",
    pain_proof_2: "when it was written",
    pain_proof_3: "that it was not changed",    breakthrough_title: "The breakthrough",
    breakthrough_text_html: "What if you could cryptographically lock information so it <strong>won't open</strong> and <strong>can't be changed</strong>?",
    breakthrough_list_1: "Create a capsule with text, files, photos, or video",
    breakthrough_list_2: "Lock by time",
    breakthrough_list_3: "Lock by location",
    breakthrough_list_4: "Lock by password (combine with AND/OR)",
    breakthrough_note: "Until conditions are met, the content stays locked — but anyone can verify it exists.",
    cases_title: "Three flagship use cases",
    cases_subtitle: "Clear real-world scenarios that users understand in seconds.",
    case1_label: "Use case 1",
    case1_title: "Proof Capsules",
    case1_headline: "Publish predictions with proof.",
    case1_step1: "Create a trading signal",
    case1_step2: "Lock it by time and password",
    case1_step3: "Publish the capsule publicly",
    case1_step4: "Share the password later",
    case1_note: "Everyone sees timestamps, hash, and rules.",
    case1_tail: "When time arrives, anyone can verify you were right. No servers.",
    case2_label: "Use case 2",
    case2_title: "Event Capsules",
    case2_headline: "Turn encryption into real-world events.",
    case2_example: "Example: open a secret at Brandenburg Gate at 12:00–12:30.",
    case2_inside_title: "Inside can be:",
    case2_inside_1: "Prize or promo code",
    case2_inside_2: "Message or invitation",
    case2_inside_3: "QR for access",
    case2_inside_4: "Next step in a quest",
    case2_note: "People gather. Phones open only on spot.",
    case3_label: "Use case 3",
    case3_title: "Campaign Capsules",
    case3_headline: "Unlock by time or password.",
    case3_text: "Example: a creator locks a capsule by time AND password. Partners get early access; everyone verifies later.",
    case3_example: "TrueLock doesn't handle distribution — you share the password separately.",
    case3_note: "Trust-based access without servers.",
    audience_title: "Who is it for?",
    audience_1_title: "Creators",
    audience_1_text: "Exclusive drops, treasure hunts, IRL events.",
    audience_2_title: "Traders and tipsters",
    audience_2_text: "Signals with proof, no back-editing.",
    audience_3_title: "Teams",
    audience_3_text: "Timed releases, secure handoffs, compliance.",
    audience_4_title: "Everyone else",
    audience_4_text: "Private messages that open later.",
    security_title: "Security & Trust",
    security_subtitle: "Built for proof, not promises.",
    security_block1_title: "Built for proof, not promises",
    security_block1_html: "<p>TrueLock is designed not just to encrypt data, but to help prove integrity, origin, and immutability.</p><ul><li>When it was created</li><li>That it wasn’t modified</li><li>That it followed the rules you set</li></ul><p class=\"micro\">No accounts. No servers. No trust required.</p>",
    security_block2_title: "Modern cryptographic standards",
    security_block2_html: "<ul><li>AES-256-GCM — authenticated encryption</li><li>PBKDF2 — password-based key derivation</li><li>SHA-256 / SHA-512 — hashing and integrity</li><li>Secure random nonces & salts</li><li>Authenticated headers to deter tampering</li></ul><p class=\"micro\">If a single byte changes, verification is expected to fail.</p>",
    security_block3_title: "Hardware-backed protection (when available)",
    security_block3_html: "<p>On supported platforms, TrueLock can use hardware-backed protection.</p><ul><li>Secure Enclave on iOS</li><li>TPM / OS-level security modules on desktop</li><li>Secure storage on Android</li></ul><ul><li>Keys are not logged</li><li>Not hardcoded</li><li>Cleared from memory where possible</li></ul>",
    security_block4_title: "Verifiable integrity — over time",
    security_block4_html: "<p>Capsules are verifiable offline — now or later.</p><ul><li>No cloud dependency</li><li>No server to trust</li><li>No account required</li></ul><p class=\"micro\">Verification is always free.</p>",
    security_block5_title: "Tamper & replay resistance",
    security_block5_html: "<ul><li>Tampering → detected by authenticated encryption</li><li>Replay attacks → reduced by unique nonces</li><li>Timing attacks → mitigated where possible</li><li>Partial extraction → breaks verification</li></ul><p class=\"micro\">If someone tries to fake or re-package a capsule, verification should fail.</p>",
    security_block6_title: "Privacy by design",
    security_block6_html: "<ul><li>No tracking</li><li>No analytics SDKs inside capsules</li><li>No hidden metadata injection</li><li>No server-side logging of content</li></ul><p class=\"micro\">What you lock is known only to you and the recipient.</p>",
    security_block7_title: "Transparent & auditable",
    security_block7_html: "<p>Security decisions are explicit and designed to be audited. Capsule format and crypto flow are documented.</p><p class=\"micro\">Trust comes from verifiability, not marketing.</p>",
    security_block8_title: "What this means for users",
    security_block8_html: "<ul><li>You don’t need to believe anything</li><li>You don’t need to trust a company</li><li>You don’t need an account</li></ul><p class=\"micro\">You can prove: it existed at a moment, it wasn’t changed, rules were enforced.</p>",
    security_summary_title: "Summary",
    security_summary_html: "<ul><li>Modern cryptography</li><li>Offline-first, serverless verification</li><li>Hardware-backed protection when available</li><li>Privacy-by-design</li><li>Proof over promises</li></ul>",
    pricing_title: "Simple pricing",
    pricing_subtitle: "Free to open and verify. Pro for advanced creation.",
    pricing_free_title: "Free",
    pricing_free_price: "$0",
    pricing_free_item1: "Open and verify any capsule",
    pricing_free_item2: "Decrypt files you receive",
    pricing_free_item3: "No account required",
    pricing_pro_title: "Pro",
    pricing_pro_price: "$9.99 one-time • 1 device",
    pricing_pro_item1: "Create capsules with time, place, or password locks",
    pricing_pro_item2: "Attach files, photos, and video",
    pricing_pro_item3: "Combine rules with AND/OR",
    pricing_pro_item4: "Batch and archive workflows",
    pricing_pro_note: "One-time license. No subscription.",
    pricing_cta: "Unlock Pro",
    download_title: "Download TrueLock",
    download_text: "Choose your platform. Works offline.",
    download_android: "Download for Android",
    download_ios: "Download for iOS",
    download_windows: "Download for Windows",
    download_macos: "Download for macOS",
    download_linux: "Download for Linux",
    final_title: "Create your first capsule in 30 seconds.",
    final_text: "Prove what you knew. Unlock when it should open.",
    final_cta: "Create a Capsule",
    footer_tagline: "No servers • No accounts • Offline-first",
    footer_copy: "© 2026 TrueLock"
  },
  ru: {    meta_title: "TrueLock — капсулы доверия",
    meta_description: "Блокируйте информацию по времени, месту или паролю. Докажите, что она существовала до событий.",
    logo_alt: "Логотип TrueLock",
    nav_pain: "Проблема",
    nav_breakthrough: "Прорыв",
    nav_cases: "Сценарии",
    nav_security: "Безопасность",
    nav_pricing: "Цены",
    nav_download: "Скачать",
    cta_primary: "Создать капсулу",
    cta_secondary: "Как это работает",
    hero_eyebrow: "Доказательство до события",
    hero_title: "TrueLock — капсулы доверия для реального мира",
    hero_subtitle_html: "Блокируйте информацию по <strong>времени</strong>, <strong>месту</strong> или <strong>паролю</strong>. Докажите, что она существовала до событий.",
    hero_note: "Без аккаунтов. Работает офлайн. Расшифровка и проверка бесплатны.",
    hero_card_1_title: "Создай",
    hero_card_1_desc: "Добавь текст, файлы, фото или видео.",
    hero_card_2_title: "Заблокируй",
    hero_card_2_desc: "Задай правила: время, место, пароль, AND/OR.",
    hero_card_3_title: "Отправь",
    hero_card_3_desc: "Отправляй куда угодно. Открытие бесплатно.",
    pain_title: "Интернет полон заявлений. Но доказательств нет.",
    pain_subtitle: "Каждый день:",
    pain_list_1: "Трейдеры подделывают прибыльные сигналы",
    pain_list_2: "Капперы редактируют прогнозы после матчей",
    pain_list_3: "Инфлюенсеры обещают эксклюзивные дропы",
    pain_list_4: "Маркетологи запускают \"реальные\" кампании",
    pain_list_5: "Журналисты не могут доказать, кто что знал и когда",
    pain_statement_title: "Одна и та же проблема везде: прошлое можно изменить.",
    pain_statement_text: "Скриншоты, посты, PDF, документы — всё можно отредактировать, удалить или подделать.",
    pain_proof_title: "Невозможно доказать:",
    pain_proof_1: "что было написано",
    pain_proof_2: "когда это было написано",
    pain_proof_3: "что это не меняли",    breakthrough_title: "Прорыв",
    breakthrough_text_html: "Что если можно криптографически заблокировать информацию так, что она <strong>не откроется</strong> и <strong>не изменится</strong>?",
    breakthrough_list_1: "Создай капсулу с текстом, файлами, фото или видео",
    breakthrough_list_2: "Блокировка по времени",
    breakthrough_list_3: "Блокировка по месту",
    breakthrough_list_4: "Блокировка по паролю (комбинируй AND/OR)",
    breakthrough_note: "Пока условия не выполнены, контент закрыт — но любой может проверить, что он существует.",
    cases_title: "Три ключевых сценария",
    cases_subtitle: "Понятные примеры из реального мира — за секунды.",
    case1_label: "Сценарий 1",
    case1_title: "Proof Capsules",
    case1_headline: "Публикуй прогнозы с доказательством.",
    case1_step1: "Создай торговый сигнал",
    case1_step2: "Заблокируй по времени и паролю",
    case1_step3: "Опубликуй капсулу публично",
    case1_step4: "Поделись паролем позже",
    case1_note: "Все видят таймстемпы, хеш и правила.",
    case1_tail: "Когда наступит время, любой проверит правоту. Без серверов.",
    case2_label: "Сценарий 2",
    case2_title: "Event Capsules",
    case2_headline: "Преврати шифрование в офлайн-события.",
    case2_example: "Пример: открыть секрет у Бранденбургских ворот в 12:00–12:30.",
    case2_inside_title: "Внутри может быть:",
    case2_inside_1: "Приз или промокод",
    case2_inside_2: "Сообщение или приглашение",
    case2_inside_3: "QR для доступа",
    case2_inside_4: "Следующий шаг квеста",
    case2_note: "Люди собираются. Телефоны открывают только на месте.",
    case3_label: "Сценарий 3",
    case3_title: "Campaign Capsules",
    case3_headline: "Открытие по времени или паролю.",
    case3_text: "Пример: создатель блокирует капсулу по времени И паролю. Партнёры получают ранний доступ, остальные проверяют позже.",
    case3_example: "TrueLock не занимается распространением — пароль делится отдельно.",
    case3_note: "Доступ на доверии без серверов.",
    audience_title: "Для кого это?",
    audience_1_title: "Создатели",
    audience_1_text: "Эксклюзивные дропы, охоты за сокровищами, IRL-ивенты.",
    audience_2_title: "Трейдеры и капперы",
    audience_2_text: "Сигналы с доказательством, без правок задним числом.",
    audience_3_title: "Команды",
    audience_3_text: "Тайминг-релизы, безопасные передачи, комплаенс.",
    audience_4_title: "Все остальные",
    audience_4_text: "Личные сообщения, которые откроются позже.",
    security_title: "Безопасность и доверие",
    security_subtitle: "Создано для доказательств, а не обещаний.",
    security_block1_title: "Создано для доказательств, а не обещаний",
    security_block1_html: "<p>TrueLock создан не только для шифрования, но и чтобы помогать доказывать целостность, происхождение и неизменность.</p><ul><li>Когда это было создано</li><li>Что это не изменялось</li><li>Что соблюдены заданные правила</li></ul><p class=\"micro\">Без аккаунтов. Без серверов. Без доверия к третьей стороне.</p>",
    security_block2_title: "Современные крипто-стандарты",
    security_block2_html: "<ul><li>AES-256-GCM — аутентифицированное шифрование</li><li>PBKDF2 — вывод ключей из пароля</li><li>SHA-256 / SHA-512 — хеширование и целостность</li><li>Случайные nonce и salt для каждой капсулы</li><li>Аутентифицированные заголовки против подмены</li></ul><p class=\"micro\">При изменении байта проверка должна провалиться.</p>",
    security_block3_title: "Аппаратная защита (когда доступна)",
    security_block3_html: "<p>На поддерживаемых платформах TrueLock может использовать аппаратную защиту.</p><ul><li>Secure Enclave на iOS</li><li>TPM / системные модули безопасности на десктопе</li><li>Secure storage на Android</li></ul><ul><li>Ключи не логируются</li><li>Не хардкодятся</li><li>Очищаются из памяти, где это возможно</li></ul>",
    security_block4_title: "Проверяемая целостность — со временем",
    security_block4_html: "<p>Капсулы проверяются оффлайн — сейчас или позже.</p><ul><li>Без облака</li><li>Без сервера, которому нужно доверять</li><li>Без аккаунта</li></ul><p class=\"micro\">Проверка всегда бесплатна.</p>",
    security_block5_title: "Защита от подмены и повторов",
    security_block5_html: "<ul><li>Подмена → обнаруживается аутентифицированным шифрованием</li><li>Replay-атаки → снижены уникальными nonce</li><li>Timing-атаки → снижены там, где это возможно</li><li>Частичное извлечение → ломает проверку</li></ul><p class=\"micro\">Попытка подделки обычно приводит к провалу проверки.</p>",
    security_block6_title: "Приватность по умолчанию",
    security_block6_html: "<ul><li>Без трекинга</li><li>Без аналитических SDK внутри капсул</li><li>Без скрытой подстановки метаданных</li><li>Без серверного логирования контента</li></ul><p class=\"micro\">То, что ты закрываешь, известно только тебе и получателю.</p>",
    security_block7_title: "Прозрачно и аудируемо",
    security_block7_html: "<p>Решения безопасности явные и рассчитаны на аудит. Формат капсулы и крипто-поток документируются.</p><p class=\"micro\">Доверие строится на проверяемости, а не на маркетинге.</p>",
    security_block8_title: "Что это значит для пользователей",
    security_block8_html: "<ul><li>Не нужно верить на слово</li><li>Не нужно доверять компании</li><li>Не нужен аккаунт</li></ul><p class=\"micro\">Можно доказать: контент существовал, не менялся и правила соблюдены.</p>",
    security_summary_title: "Итог",
    security_summary_html: "<ul><li>Современная криптография</li><li>Оффлайн-проверка без серверов</li><li>Аппаратная защита, когда доступна</li><li>Приватность по умолчанию</li><li>Доказательство вместо обещаний</li></ul>",
    pricing_title: "Простые цены",
    pricing_subtitle: "Открытие и проверка — бесплатно. Pro для создания.",
    pricing_free_title: "Бесплатно",
    pricing_free_price: "$0",
    pricing_free_item1: "Открывай и проверяй любые капсулы",
    pricing_free_item2: "Расшифровывай полученные файлы",
    pricing_free_item3: "Без аккаунта",
    pricing_pro_title: "Pro",
    pricing_pro_price: "$9.99 разово • 1 устройство",
    pricing_pro_item1: "Создавай капсулы с блокировкой по времени, месту или паролю",
    pricing_pro_item2: "Прикрепляй файлы, фото и видео",
    pricing_pro_item3: "Комбинируй правила AND/OR",
    pricing_pro_item4: "Пакетные и архивные сценарии",
    pricing_pro_note: "Разовая лицензия. Без подписки.",
    pricing_cta: "Открыть Pro",
    download_title: "Скачать TrueLock",
    download_text: "Выбери платформу. Работает офлайн.",
    download_android: "Скачать для Android",
    download_ios: "Скачать для iOS",
    download_windows: "Скачать для Windows",
    download_macos: "Скачать для macOS",
    download_linux: "Скачать для Linux",
    final_title: "Создай первую капсулу за 30 секунд.",
    final_text: "Докажи, что знал. Открой в нужный момент.",
    final_cta: "Создать капсулу",
    footer_tagline: "Без серверов • Без аккаунтов • Offline-first",
    footer_copy: "© 2026 TrueLock"
  },
  de: {    meta_title: "TrueLock — Vertrauenskapseln",
    meta_description: "Sperre Informationen nach Zeit, Ort oder Passwort. Beweise, dass sie vor dem Ereignis existierten.",
    logo_alt: "TrueLock Logo",
    nav_pain: "Problem",
    nav_breakthrough: "Durchbruch",
    nav_cases: "Anwendungsfälle",
    nav_security: "Sicherheit",
    nav_pricing: "Preise",
    nav_download: "Download",
    cta_primary: "Kapsel erstellen",
    cta_secondary: "So funktioniert es",
    hero_eyebrow: "Beweis vor dem Ereignis",
    hero_title: "TrueLock — Vertrauenskapseln für die reale Welt",
    hero_subtitle_html: "Sperre Informationen nach <strong>Zeit</strong>, <strong>Ort</strong> oder <strong>Passwort</strong>. Beweise, dass sie vor dem Ereignis existierten.",
    hero_note: "Keine Accounts. Funktioniert offline. Entschlüsseln und Verifizieren sind kostenlos.",
    hero_card_1_title: "Erstellen",
    hero_card_1_desc: "Text, Dateien, Fotos oder Videos hinzufügen.",
    hero_card_2_title: "Sperren",
    hero_card_2_desc: "Regeln setzen: Zeit, Ort, Passwort, AND/OR.",
    hero_card_3_title: "Teilen",
    hero_card_3_desc: "Überall teilen. Kostenlos öffnen.",
    pain_title: "Das Internet ist voller Behauptungen. Aber es gibt keinen Beweis.",
    pain_subtitle: "Jeden Tag:",
    pain_list_1: "Trader fälschen Gewinnsignale",
    pain_list_2: "Tipster bearbeiten Prognosen nach dem Spiel",
    pain_list_3: "Influencer versprechen exklusive Drops",
    pain_list_4: "Marketer führen \"echte\" Kampagnen",
    pain_list_5: "Journalisten können nicht beweisen, wer was wann wusste",
    pain_statement_title: "Dasselbe Problem überall: Jeder kann die Vergangenheit ändern.",
    pain_statement_text: "Screenshots, Posts, PDFs, Dokumente — alles kann bearbeitet, gelöscht oder gefälscht werden.",
    pain_proof_title: "Es gibt keinen Weg zu beweisen:",
    pain_proof_1: "was geschrieben wurde",
    pain_proof_2: "wann es geschrieben wurde",
    pain_proof_3: "dass es nicht verändert wurde",    breakthrough_title: "Der Durchbruch",
    breakthrough_text_html: "Was wäre, wenn man Informationen kryptografisch so sperren könnte, dass sie <strong>nicht geöffnet werden</strong> und <strong>nicht verändert werden können</strong>?",
    breakthrough_list_1: "Erstelle eine Kapsel mit Text, Dateien, Fotos oder Video",
    breakthrough_list_2: "Sperre nach Zeit",
    breakthrough_list_3: "Sperre nach Ort",
    breakthrough_list_4: "Sperre nach Passwort (AND/OR kombinieren)",
    breakthrough_note: "Bis die Bedingungen erfüllt sind, bleibt der Inhalt gesperrt — aber jeder kann prüfen, dass er existiert.",
    cases_title: "Drei zentrale Use Cases",
    cases_subtitle: "Klare reale Szenarien, in Sekunden verstanden.",
    case1_label: "Use Case 1",
    case1_title: "Proof Capsules",
    case1_headline: "Prognosen mit Beweis veröffentlichen.",
    case1_step1: "Ein Trading-Signal erstellen",
    case1_step2: "Nach Zeit und Passwort sperren",
    case1_step3: "Kapsel öffentlich veröffentlichen",
    case1_step4: "Passwort später teilen",
    case1_note: "Alle sehen Zeitstempel, Hash und Regeln.",
    case1_tail: "Wenn die Zeit kommt, kann jeder überprüfen, dass du Recht hattest. Ohne Server.",
    case2_label: "Use Case 2",
    case2_title: "Event Capsules",
    case2_headline: "Verschlüsselung in reale Events verwandeln.",
    case2_example: "Beispiel: ein Geheimnis am Brandenburger Tor um 12:00–12:30 öffnen.",
    case2_inside_title: "Darin kann sein:",
    case2_inside_1: "Preis oder Promo-Code",
    case2_inside_2: "Nachricht oder Einladung",
    case2_inside_3: "QR für Zugang",
    case2_inside_4: "Nächster Schritt einer Quest",
    case2_note: "Menschen kommen zusammen. Handys öffnen nur vor Ort.",
    case3_label: "Use Case 3",
    case3_title: "Campaign Capsules",
    case3_headline: "Öffnen nach Zeit oder Passwort.",
    case3_text: "Beispiel: Ein Creator sperrt eine Kapsel nach Zeit UND Passwort. Partner erhalten früh Zugriff; alle anderen prüfen später.",
    case3_example: "TrueLock übernimmt keine Verteilung — das Passwort teilst du separat.",
    case3_note: "Vertrauensbasierter Zugang ohne Server.",
    audience_title: "Für wen ist es?",
    audience_1_title: "Creator",
    audience_1_text: "Exklusive Drops, Schatzsuchen, IRL-Events.",
    audience_2_title: "Trader und Tipster",
    audience_2_text: "Signale mit Beweis, ohne Nachbearbeitung.",
    audience_3_title: "Teams",
    audience_3_text: "Zeitgesteuerte Releases, sichere Übergaben, Compliance.",
    audience_4_title: "Alle anderen",
    audience_4_text: "Private Nachrichten, die später öffnen.",
    security_title: "Sicherheit ohne Hype",
    security_subtitle: "Für Beweise, nicht für Versprechen.",
    security_block1_title: "Für Beweise, nicht für Versprechen",
    security_block1_html: "<p>TrueLock wurde nicht nur zur Verschlüsselung entwickelt, sondern um Integrität, Herkunft und Unveränderlichkeit nachweisbar zu machen.</p><ul><li>Wann es erstellt wurde</li><li>Dass es nicht verändert wurde</li><li>Dass es den von dir gesetzten Regeln folgte</li></ul><p class=\"micro\">Keine Accounts. Keine Server. Kein Vertrauen nötig.</p>",
    security_block2_title: "Moderne Kryptografie-Standards",
    security_block2_html: "<ul><li>AES-256-GCM — authentifizierte Verschlüsselung</li><li>PBKDF2 — Schlüsselableitung aus Passwörtern</li><li>SHA-256 / SHA-512 — Hashing und Integrität</li><li>Sichere zufällige Nonces & Salts</li><li>Authentifizierte Header gegen Manipulation</li></ul><p class=\"micro\">Wenn ein Byte geändert wird, sollte die Prüfung fehlschlagen.</p>",
    security_block3_title: "Hardware‑gestützte Sicherheit (wenn verfügbar)",
    security_block3_html: "<p>Auf unterstützten Plattformen kann TrueLock hardware‑gestützte Sicherheit nutzen.</p><ul><li>Secure Enclave auf iOS</li><li>TPM / System‑Sicherheitsmodule auf Desktop</li><li>Secure Storage auf Android</li></ul><ul><li>Schlüssel werden nicht geloggt</li><li>Nicht hardcodiert</li><li>Wenn möglich nach Nutzung aus dem Speicher gelöscht</li></ul>",
    security_block4_title: "Nachweisbare Integrität — über die Zeit",
    security_block4_html: "<p>Kapseln sind offline überprüfbar — jetzt oder später.</p><ul><li>Keine Cloud‑Abhängigkeit</li><li>Kein Server, dem man vertrauen muss</li><li>Kein Account erforderlich</li></ul><p class=\"micro\">Die Verifikation ist immer kostenlos.</p>",
    security_block5_title: "Manipulations‑ und Replay‑Schutz",
    security_block5_html: "<ul><li>Manipulation → durch authentifizierte Verschlüsselung erkennbar</li><li>Replay‑Angriffe → durch einzigartige Nonces reduziert</li><li>Timing‑Angriffe → wo möglich reduziert</li><li>Teilweise Extraktion → bricht die Verifikation</li></ul><p class=\"micro\">Wenn jemand versucht, eine Kapsel zu fälschen oder neu zu verpacken, sollte die Prüfung fehlschlagen.</p>",
    security_block6_title: "Datenschutz by design",
    security_block6_html: "<ul><li>Kein Tracking</li><li>Keine Analytics‑SDKs in Kapseln</li><li>Keine versteckte Metadaten‑Injection</li><li>Kein serverseitiges Logging von Inhalten</li></ul><p class=\"micro\">Was du sperrst, ist nur dir und dem Empfänger bekannt.</p>",
    security_block7_title: "Transparent & auditierbar",
    security_block7_html: "<p>Sicherheitsentscheidungen sind explizit und auf Audit ausgelegt. Kapsel‑Format und Crypto‑Flow sind dokumentiert.</p><p class=\"micro\">Vertrauen kommt von Nachprüfbarkeit, nicht von Marketing.</p>",
    security_block8_title: "Was das für Nutzer bedeutet",
    security_block8_html: "<ul><li>Du musst nichts glauben</li><li>Du musst keinem Unternehmen vertrauen</li><li>Du brauchst keinen Account</li></ul><p class=\"micro\">Du kannst beweisen: es existierte, wurde nicht verändert, Regeln wurden eingehalten.</p>",
    security_summary_title: "Zusammenfassung",
    security_summary_html: "<ul><li>Moderne Kryptografie</li><li>Offline‑Verifikation ohne Server</li><li>Hardware‑gestützte Sicherheit, wenn verfügbar</li><li>Datenschutz by Design</li><li>Beweise statt Versprechen</li></ul>",
    pricing_title: "Einfache Preise",
    pricing_subtitle: "Öffnen & Verifizieren ist gratis. Pro für das Erstellen.",
    pricing_free_title: "Gratis",
    pricing_free_price: "$0",
    pricing_free_item1: "Beliebige Kapseln öffnen und verifizieren",
    pricing_free_item2: "Erhaltene Dateien entschlüsseln",
    pricing_free_item3: "Kein Account erforderlich",
    pricing_pro_title: "Pro",
    pricing_pro_price: "$9.99 einmalig • 1 Gerät",
    pricing_pro_item1: "Kapseln mit Zeit-, Orts- oder Passwort-Sperre erstellen",
    pricing_pro_item2: "Dateien, Fotos und Videos anhängen",
    pricing_pro_item3: "Regeln mit AND/OR kombinieren",
    pricing_pro_item4: "Batch- und Archiv-Workflows",
    pricing_pro_note: "Einmalige Lizenz. Kein Abo.",
    pricing_cta: "Pro freischalten",
    download_title: "TrueLock herunterladen",
    download_text: "Plattform wählen. Funktioniert offline.",
    download_android: "Für Android herunterladen",
    download_ios: "Für iOS herunterladen",
    download_windows: "Für Windows herunterladen",
    download_macos: "Für macOS herunterladen",
    download_linux: "Für Linux herunterladen",
    final_title: "Erstelle deine erste Kapsel in 30 Sekunden.",
    final_text: "Beweise, was du wusstest. Öffne, wenn es passt.",
    final_cta: "Kapsel erstellen",
    footer_tagline: "Keine Server • Keine Accounts • Offline-first",
    footer_copy: "© 2026 TrueLock"
  },
  es: {    meta_title: "TrueLock — Cápsulas de confianza",
    meta_description: "Bloquea información por tiempo, lugar o contraseña. Demuestra que existía antes del evento.",
    logo_alt: "Logo de TrueLock",
    nav_pain: "Problema",
    nav_breakthrough: "Avance",
    nav_cases: "Casos de uso",
    nav_security: "Seguridad",
    nav_pricing: "Precios",
    nav_download: "Descargar",
    cta_primary: "Crear cápsula",
    cta_secondary: "Ver cómo funciona",
    hero_eyebrow: "Prueba antes del evento",
    hero_title: "TrueLock — Cápsulas de confianza para el mundo real",
    hero_subtitle_html: "Bloquea información por <strong>tiempo</strong>, <strong>lugar</strong> o <strong>contraseña</strong>. Demuestra que existía antes del evento.",
    hero_note: "Sin cuentas. Funciona offline. Desencriptar y verificar es gratis.",
    hero_card_1_title: "Crear",
    hero_card_1_desc: "Añade texto, archivos, fotos o video.",
    hero_card_2_title: "Bloquear",
    hero_card_2_desc: "Define reglas: tiempo, ubicación, contraseña, AND/OR.",
    hero_card_3_title: "Compartir",
    hero_card_3_desc: "Envía la cápsula a cualquier lugar. Se abre gratis.",
    pain_title: "Internet está lleno de afirmaciones. Pero no hay pruebas.",
    pain_subtitle: "Cada día:",
    pain_list_1: "Traders falsifican señales ganadoras",
    pain_list_2: "Tipsters editan predicciones después del partido",
    pain_list_3: "Influencers prometen drops exclusivos",
    pain_list_4: "Marketers lanzan campañas \"reales\"",
    pain_list_5: "Periodistas no pueden probar quién sabía qué y cuándo",
    pain_statement_title: "El mismo problema en todas partes: cualquiera puede cambiar el pasado.",
    pain_statement_text: "Capturas, posts, PDFs, documentos — todo puede editarse, borrarse o falsificarse.",
    pain_proof_title: "No hay forma de probar:",
    pain_proof_1: "qué se escribió",
    pain_proof_2: "cuándo se escribió",
    pain_proof_3: "que no se cambió",    breakthrough_title: "El avance",
    breakthrough_text_html: "¿Y si pudieras bloquear información criptográficamente para que <strong>no se abra</strong> y <strong>no pueda cambiarse</strong>?",
    breakthrough_list_1: "Crea una cápsula con texto, archivos, fotos o video",
    breakthrough_list_2: "Bloqueo por tiempo",
    breakthrough_list_3: "Bloqueo por ubicación",
    breakthrough_list_4: "Bloqueo por contraseña (combina AND/OR)",
    breakthrough_note: "Hasta que se cumplan las condiciones, el contenido queda bloqueado — pero cualquiera puede verificar que existe.",
    cases_title: "Tres casos emblemáticos",
    cases_subtitle: "Escenarios reales claros, comprensibles en segundos.",
    case1_label: "Caso 1",
    case1_title: "Proof Capsules",
    case1_headline: "Publica predicciones con prueba.",
    case1_step1: "Crea una señal de trading",
    case1_step2: "Bloquéala por tiempo y contraseña",
    case1_step3: "Publica la cápsula en público",
    case1_step4: "Comparte la contraseña después",
    case1_note: "Todos ven marcas de tiempo, hash y reglas.",
    case1_tail: "Cuando llegue el momento, cualquiera puede verificar que tenías razón. Sin servidores.",
    case2_label: "Caso 2",
    case2_title: "Event Capsules",
    case2_headline: "Convierte el cifrado en eventos reales.",
    case2_example: "Ejemplo: abrir un secreto en la Puerta de Brandeburgo a las 12:00–12:30.",
    case2_inside_title: "Dentro puede haber:",
    case2_inside_1: "Premio o código promo",
    case2_inside_2: "Mensaje o invitación",
    case2_inside_3: "QR para acceso",
    case2_inside_4: "Siguiente paso en una misión",
    case2_note: "La gente se reúne. Los teléfonos abren solo en el lugar.",
    case3_label: "Caso 3",
    case3_title: "Campaign Capsules",
    case3_headline: "Se abre por tiempo o contraseña.",
    case3_text: "Ejemplo: un creador bloquea una cápsula por tiempo Y contraseña. Los socios tienen acceso temprano; todos verifican después.",
    case3_example: "TrueLock no gestiona la distribución — compartes la contraseña aparte.",
    case3_note: "Acceso basado en confianza sin servidores.",
    audience_title: "¿Para quién es?",
    audience_1_title: "Creadores",
    audience_1_text: "Drops exclusivos, búsquedas del tesoro, eventos IRL.",
    audience_2_title: "Traders y tipsters",
    audience_2_text: "Señales con prueba, sin edición posterior.",
    audience_3_title: "Equipos",
    audience_3_text: "Lanzamientos programados, traspasos seguros, compliance.",
    audience_4_title: "Todos los demás",
    audience_4_text: "Mensajes privados que se abren después.",
    security_title: "Seguridad sin humo",
    security_subtitle: "Creado para pruebas, no promesas.",
    security_block1_title: "Creado para pruebas, no promesas",
    security_block1_html: "<p>TrueLock no solo cifra datos; está diseñado para ayudar a demostrar integridad, origen e inmutabilidad.</p><ul><li>Cuándo se creó</li><li>Que no se modificó</li><li>Que siguió las reglas que definiste</li></ul><p class=\"micro\">Sin cuentas. Sin servidores. Sin confianza requerida.</p>",
    security_block2_title: "Criptografía moderna basada en estándares",
    security_block2_html: "<ul><li>AES-256-GCM — cifrado autenticado</li><li>PBKDF2 — derivación de claves desde contraseña</li><li>SHA-256 / SHA-512 — hashing e integridad</li><li>Nonces y salts aleatorios seguros</li><li>Cabeceras autenticadas contra manipulación</li></ul><p class=\"micro\">Si un byte cambia, la verificación debería fallar.</p>",
    security_block3_title: "Protección con hardware (cuando esté disponible)",
    security_block3_html: "<p>En plataformas compatibles, TrueLock puede usar protección con hardware.</p><ul><li>Secure Enclave en iOS</li><li>TPM / módulos de seguridad del sistema en desktop</li><li>Secure storage en Android</li></ul><ul><li>Las claves no se registran</li><li>No se hardcodean</li><li>Se borran de memoria cuando es posible</li></ul>",
    security_block4_title: "Integridad verificable — con el tiempo",
    security_block4_html: "<p>Las cápsulas se pueden verificar offline — ahora o después.</p><ul><li>Sin dependencia de la nube</li><li>Sin servidor en quien confiar</li><li>Sin cuenta requerida</li></ul><p class=\"micro\">La verificación siempre es gratis.</p>",
    security_block5_title: "Resistencia a manipulación y replay",
    security_block5_html: "<ul><li>Manipulación → detectada por cifrado autenticado</li><li>Ataques replay → reducidos con nonces únicos</li><li>Ataques de timing → mitigados cuando es posible</li><li>Extracción parcial → rompe la verificación</li></ul><p class=\"micro\">Si alguien intenta falsificar o re‑empaquetar una cápsula, la verificación debería fallar.</p>",
    security_block6_title: "Privacidad por diseño",
    security_block6_html: "<ul><li>Sin tracking</li><li>Sin SDKs de analítica dentro de cápsulas</li><li>Sin inyección oculta de metadatos</li><li>Sin logging de contenido en servidor</li></ul><p class=\"micro\">Lo que bloqueas es conocido solo por ti y el destinatario.</p>",
    security_block7_title: "Transparente y auditable",
    security_block7_html: "<p>Las decisiones de seguridad son explícitas y pensadas para auditoría. El formato de la cápsula y el flujo criptográfico están documentados.</p><p class=\"micro\">La confianza viene de la verificación, no del marketing.</p>",
    security_block8_title: "Qué significa para los usuarios",
    security_block8_html: "<ul><li>No necesitas creer nada</li><li>No necesitas confiar en una empresa</li><li>No necesitas cuenta</li></ul><p class=\"micro\">Puedes demostrar: existía en un momento, no cambió y las reglas se aplicaron.</p>",
    security_summary_title: "Resumen",
    security_summary_html: "<ul><li>Criptografía moderna</li><li>Verificación offline sin servidores</li><li>Protección con hardware cuando esté disponible</li><li>Privacidad por diseño</li><li>Prueba sobre promesas</li></ul>",
    pricing_title: "Precios simples",
    pricing_subtitle: "Abrir y verificar es gratis. Pro para crear.",
    pricing_free_title: "Gratis",
    pricing_free_price: "$0",
    pricing_free_item1: "Abrir y verificar cualquier cápsula",
    pricing_free_item2: "Descifrar archivos recibidos",
    pricing_free_item3: "Sin cuenta",
    pricing_pro_title: "Pro",
    pricing_pro_price: "$9.99 pago único • 1 dispositivo",
    pricing_pro_item1: "Crear cápsulas con bloqueo por tiempo, lugar o contraseña",
    pricing_pro_item2: "Adjuntar archivos, fotos y video",
    pricing_pro_item3: "Combinar reglas con AND/OR",
    pricing_pro_item4: "Flujos por lotes y archivos",
    pricing_pro_note: "Licencia de pago único. Sin suscripción.",
    pricing_cta: "Desbloquear Pro",
    download_title: "Descargar TrueLock",
    download_text: "Elige tu plataforma. Funciona offline.",
    download_android: "Descargar para Android",
    download_ios: "Descargar para iOS",
    download_windows: "Descargar para Windows",
    download_macos: "Descargar para macOS",
    download_linux: "Descargar para Linux",
    final_title: "Crea tu primera cápsula en 30 segundos.",
    final_text: "Demuestra lo que sabías. Abre cuando deba abrirse.",
    final_cta: "Crear cápsula",
    footer_tagline: "Sin servidores • Sin cuentas • Offline-first",
    footer_copy: "© 2026 TrueLock"
  },
  fr: {    meta_title: "TrueLock — Capsules de confiance",
    meta_description: "Verrouillez l’information par temps, lieu ou mot de passe. Prouvez qu’elle existait avant l’événement.",
    logo_alt: "Logo TrueLock",
    nav_pain: "Problème",
    nav_breakthrough: "Percée",
    nav_cases: "Cas d’usage",
    nav_security: "Sécurité",
    nav_pricing: "Tarifs",
    nav_download: "Télécharger",
    cta_primary: "Créer une capsule",
    cta_secondary: "Voir comment ça marche",
    hero_eyebrow: "La preuve avant l’événement",
    hero_title: "TrueLock — Capsules de confiance pour le monde réel",
    hero_subtitle_html: "Verrouillez l’information par <strong>temps</strong>, <strong>lieu</strong> ou <strong>mot de passe</strong>. Prouvez qu’elle existait avant l’événement.",
    hero_note: "Pas de comptes. Fonctionne hors ligne. Déchiffrer et vérifier est gratuit.",
    hero_card_1_title: "Créer",
    hero_card_1_desc: "Ajoutez du texte, des fichiers, des photos ou des vidéos.",
    hero_card_2_title: "Verrouiller",
    hero_card_2_desc: "Définir des règles : temps, lieu, mot de passe, AND/OR.",
    hero_card_3_title: "Partager",
    hero_card_3_desc: "Envoyez la capsule n’importe où. Ouverture gratuite.",
    pain_title: "Internet est rempli d’affirmations. Mais il n’y a pas de preuve.",
    pain_subtitle: "Chaque jour :",
    pain_list_1: "Des traders falsifient des signaux gagnants",
    pain_list_2: "Des tipsters modifient les prédictions après le match",
    pain_list_3: "Des influenceurs promettent des drops exclusifs",
    pain_list_4: "Des marketeurs lancent des campagnes \"réelles\"",
    pain_list_5: "Les journalistes ne peuvent pas prouver qui savait quoi et quand",
    pain_statement_title: "Le même problème partout : tout le monde peut changer le passé.",
    pain_statement_text: "Captures d’écran, posts, PDF, documents — tout peut être édité, supprimé ou falsifié.",
    pain_proof_title: "Impossible de prouver :",
    pain_proof_1: "ce qui a été écrit",
    pain_proof_2: "quand cela a été écrit",
    pain_proof_3: "que cela n’a pas été modifié",    breakthrough_title: "La percée",
    breakthrough_text_html: "Et si vous pouviez verrouiller l’information cryptographiquement pour qu’elle <strong>ne s’ouvre pas</strong> et <strong>ne puisse pas être modifiée</strong> ?",
    breakthrough_list_1: "Créez une capsule avec du texte, des fichiers, des photos ou des vidéos",
    breakthrough_list_2: "Verrouillage par temps",
    breakthrough_list_3: "Verrouillage par lieu",
    breakthrough_list_4: "Verrouillage par mot de passe (AND/OR)",
    breakthrough_note: "Tant que les conditions ne sont pas remplies, le contenu reste verrouillé — mais chacun peut vérifier qu’il existe.",
    cases_title: "Trois cas phares",
    cases_subtitle: "Des scénarios réels clairs, compris en quelques secondes.",
    case1_label: "Cas 1",
    case1_title: "Proof Capsules",
    case1_headline: "Publiez des prédictions avec preuve.",
    case1_step1: "Créer un signal de trading",
    case1_step2: "Le verrouiller par temps et mot de passe",
    case1_step3: "Publier la capsule publiquement",
    case1_step4: "Partager le mot de passe plus tard",
    case1_note: "Tout le monde voit l’horodatage, le hash et les règles.",
    case1_tail: "Quand le moment arrive, chacun peut vérifier que vous aviez raison. Sans serveurs.",
    case2_label: "Cas 2",
    case2_title: "Event Capsules",
    case2_headline: "Transformez le chiffrement en événements réels.",
    case2_example: "Exemple : ouvrir un secret à la Porte de Brandebourg de 12:00 à 12:30.",
    case2_inside_title: "À l’intérieur :",
    case2_inside_1: "Prix ou code promo",
    case2_inside_2: "Message ou invitation",
    case2_inside_3: "QR pour l’accès",
    case2_inside_4: "Prochaine étape d’une quête",
    case2_note: "Les gens se rassemblent. Les téléphones s’ouvrent uniquement sur place.",
    case3_label: "Cas 3",
    case3_title: "Campaign Capsules",
    case3_headline: "Ouverture par temps ou mot de passe.",
    case3_text: "Exemple : un créateur verrouille une capsule par temps ET mot de passe. Les partenaires ont l’accès anticipé; tout le monde vérifie ensuite.",
    case3_example: "TrueLock ne gère pas la distribution — vous partagez le mot de passe séparément.",
    case3_note: "Accès basé sur la confiance, sans serveurs.",
    audience_title: "Pour qui ?",
    audience_1_title: "Créateurs",
    audience_1_text: "Drops exclusifs, chasses au trésor, événements IRL.",
    audience_2_title: "Traders et tipsters",
    audience_2_text: "Signaux avec preuve, sans édition après coup.",
    audience_3_title: "Équipes",
    audience_3_text: "Lancements programmés, transferts sécurisés, conformité.",
    audience_4_title: "Tout le monde",
    audience_4_text: "Messages privés qui s’ouvrent plus tard.",
    security_title: "Sécurité sans hype",
    security_subtitle: "Conçu pour la preuve, pas pour les promesses.",
    security_block1_title: "Conçu pour la preuve, pas pour les promesses",
    security_block1_html: "<p>TrueLock n’est pas seulement un chiffrement : il est conçu pour aider à prouver l’intégrité, l’origine et l’immutabilité.</p><ul><li>Quand c’est créé</li><li>Que cela n’a pas été modifié</li><li>Que les règles définies ont été respectées</li></ul><p class=\"micro\">Sans comptes. Sans serveurs. Sans confiance requise.</p>",
    security_block2_title: "Cryptographie moderne basée sur des standards",
    security_block2_html: "<ul><li>AES-256-GCM — chiffrement authentifié</li><li>PBKDF2 — dérivation de clés depuis un mot de passe</li><li>SHA-256 / SHA-512 — hachage et intégrité</li><li>Nonces et salts aléatoires sécurisés</li><li>En‑têtes authentifiés contre la manipulation</li></ul><p class=\"micro\">Si un octet change, la vérification devrait échouer.</p>",
    security_block3_title: "Protection matérielle (quand disponible)",
    security_block3_html: "<p>Sur les plateformes compatibles, TrueLock peut utiliser une protection matérielle.</p><ul><li>Secure Enclave sur iOS</li><li>TPM / modules de sécurité système sur desktop</li><li>Secure storage sur Android</li></ul><ul><li>Les clés ne sont pas loggées</li><li>Pas hardcodées</li><li>Nettoyées de la mémoire quand c'est possible</li></ul>",
    security_block4_title: "Intégrité vérifiable — dans le temps",
    security_block4_html: "<p>Les capsules sont vérifiables hors‑ligne — maintenant ou plus tard.</p><ul><li>Aucune dépendance cloud</li><li>Aucun serveur à qui faire confiance</li><li>Aucun compte requis</li></ul><p class=\"micro\">La vérification est toujours gratuite.</p>",
    security_block5_title: "Résistance à la manipulation et au replay",
    security_block5_html: "<ul><li>Manipulation → détectée via chiffrement authentifié</li><li>Attaques replay → réduites par nonces uniques</li><li>Attaques de timing → atténuées quand c'est possible</li><li>Extraction partielle → casse la vérification</li></ul><p class=\"micro\">Si quelqu’un tente de falsifier ou de re‑packager, la vérification devrait échouer.</p>",
    security_block6_title: "Confidentialité par conception",
    security_block6_html: "<ul><li>Aucun tracking</li><li>Aucun SDK d’analytics dans les capsules</li><li>Aucune injection cachée de métadonnées</li><li>Aucun logging serveur du contenu</li></ul><p class=\"micro\">Ce que tu verrouilles n’est connu que de toi et du destinataire.</p>",
    security_block7_title: "Transparent et auditable",
    security_block7_html: "<p>Les décisions de sécurité sont explicites et pensées pour l’audit. Le format de la capsule et le flux cryptographique sont documentés.</p><p class=\"micro\">La confiance vient de la vérification, pas du marketing.</p>",
    security_block8_title: "Ce que cela signifie pour les utilisateurs",
    security_block8_html: "<ul><li>Pas besoin de croire</li><li>Pas besoin de faire confiance à une entreprise</li><li>Pas besoin de compte</li></ul><p class=\"micro\">Vous pouvez prouver : existence, non‑modification, règles appliquées.</p>",
    security_summary_title: "Résumé",
    security_summary_html: "<ul><li>Cryptographie moderne</li><li>Vérification offline sans serveurs</li><li>Protection matérielle quand disponible</li><li>Confidentialité dès la conception</li><li>La preuve plutôt que les promesses</li></ul>",
    pricing_title: "Tarifs simples",
    pricing_subtitle: "Ouverture et vérification gratuites. Pro pour créer.",
    pricing_free_title: "Gratuit",
    pricing_free_price: "$0",
    pricing_free_item1: "Ouvrir et vérifier n’importe quelle capsule",
    pricing_free_item2: "Déchiffrer les fichiers reçus",
    pricing_free_item3: "Aucun compte requis",
    pricing_pro_title: "Pro",
    pricing_pro_price: "$9.99 achat unique • 1 appareil",
    pricing_pro_item1: "Créer des capsules avec verrouillage temps, lieu ou mot de passe",
    pricing_pro_item2: "Joindre des fichiers, photos et vidéos",
    pricing_pro_item3: "Combiner les règles avec AND/OR",
    pricing_pro_item4: "Flux par lots et archives",
    pricing_pro_note: "Licence unique. Sans abonnement.",
    pricing_cta: "Débloquer Pro",
    download_title: "Télécharger TrueLock",
    download_text: "Choisissez votre plateforme. Fonctionne hors ligne.",
    download_android: "Télécharger pour Android",
    download_ios: "Télécharger pour iOS",
    download_windows: "Télécharger pour Windows",
    download_macos: "Télécharger pour macOS",
    download_linux: "Télécharger pour Linux",
    final_title: "Créez votre première capsule en 30 secondes.",
    final_text: "Prouvez ce que vous saviez. Ouvrez quand il faut.",
    final_cta: "Créer une capsule",
    footer_tagline: "Sans serveurs • Sans comptes • Offline-first",
    footer_copy: "© 2026 TrueLock"
  },
  it: {    meta_title: "TrueLock — Capsule di fiducia",
    meta_description: "Blocca le informazioni per tempo, luogo o password. Dimostra che esistevano prima dell’evento.",
    logo_alt: "Logo TrueLock",
    nav_pain: "Problema",
    nav_breakthrough: "Svolta",
    nav_cases: "Casi d’uso",
    nav_security: "Sicurezza",
    nav_pricing: "Prezzi",
    nav_download: "Download",
    cta_primary: "Crea una capsula",
    cta_secondary: "Vedi come funziona",
    hero_eyebrow: "Prova prima dell’evento",
    hero_title: "TrueLock — Capsule di fiducia per il mondo reale",
    hero_subtitle_html: "Blocca le informazioni per <strong>tempo</strong>, <strong>luogo</strong> o <strong>password</strong>. Dimostra che esistevano prima dell’evento.",
    hero_note: "Nessun account. Funziona offline. Decifrare e verificare è gratuito.",
    hero_card_1_title: "Crea",
    hero_card_1_desc: "Aggiungi testo, file, foto o video.",
    hero_card_2_title: "Blocca",
    hero_card_2_desc: "Imposta regole: tempo, luogo, password, AND/OR.",
    hero_card_3_title: "Condividi",
    hero_card_3_desc: "Invia la capsula ovunque. Apertura gratuita.",
    pain_title: "Internet è pieno di affermazioni. Ma non ci sono prove.",
    pain_subtitle: "Ogni giorno:",
    pain_list_1: "I trader falsificano segnali vincenti",
    pain_list_2: "I tipster modificano le previsioni dopo la partita",
    pain_list_3: "Gli influencer promettono drop esclusivi",
    pain_list_4: "I marketer lanciano campagne \"reali\"",
    pain_list_5: "I giornalisti non possono provare chi sapeva cosa e quando",
    pain_statement_title: "Lo stesso problema ovunque: chiunque può cambiare il passato.",
    pain_statement_text: "Screenshot, post, PDF, documenti — tutto può essere modificato, cancellato o falsificato.",
    pain_proof_title: "Non c’è modo di provare:",
    pain_proof_1: "cosa è stato scritto",
    pain_proof_2: "quando è stato scritto",
    pain_proof_3: "che non è stato modificato",    breakthrough_title: "La svolta",
    breakthrough_text_html: "E se potessi bloccare l’informazione crittograficamente così che <strong>non si apra</strong> e <strong>non possa essere modificata</strong>?",
    breakthrough_list_1: "Crea una capsula con testo, file, foto o video",
    breakthrough_list_2: "Blocco per tempo",
    breakthrough_list_3: "Blocco per luogo",
    breakthrough_list_4: "Blocco per password (AND/OR)",
    breakthrough_note: "Finché le condizioni non sono soddisfatte, il contenuto resta bloccato — ma chiunque può verificare che esista.",
    cases_title: "Tre casi principali",
    cases_subtitle: "Scenari reali chiari, comprensibili in pochi secondi.",
    case1_label: "Caso 1",
    case1_title: "Proof Capsules",
    case1_headline: "Pubblica previsioni con prova.",
    case1_step1: "Crea un segnale di trading",
    case1_step2: "Bloccalo per tempo e password",
    case1_step3: "Pubblica la capsula pubblicamente",
    case1_step4: "Condividi la password più tardi",
    case1_note: "Tutti vedono timestamp, hash e regole.",
    case1_tail: "Quando arriva il momento, chiunque può verificare che avevi ragione. Senza server.",
    case2_label: "Caso 2",
    case2_title: "Event Capsules",
    case2_headline: "Trasforma la crittografia in eventi reali.",
    case2_example: "Esempio: apri un segreto alla Porta di Brandeburgo alle 12:00–12:30.",
    case2_inside_title: "Dentro può esserci:",
    case2_inside_1: "Premio o codice promo",
    case2_inside_2: "Messaggio o invito",
    case2_inside_3: "QR per l’accesso",
    case2_inside_4: "Prossimo passo di una quest",
    case2_note: "Le persone si radunano. I telefoni si aprono solo sul posto.",
    case3_label: "Caso 3",
    case3_title: "Campaign Capsules",
    case3_headline: "Si sblocca per tempo o password.",
    case3_text: "Esempio: un creator blocca una capsula per tempo E password. I partner hanno accesso anticipato; tutti verificano dopo.",
    case3_example: "TrueLock non gestisce la distribuzione — la password si condivide separatamente.",
    case3_note: "Accesso basato sulla fiducia, senza server.",
    audience_title: "Per chi è?",
    audience_1_title: "Creator",
    audience_1_text: "Drop esclusivi, cacce al tesoro, eventi IRL.",
    audience_2_title: "Trader e tipster",
    audience_2_text: "Segnali con prova, senza modifiche dopo.",
    audience_3_title: "Team",
    audience_3_text: "Rilasci programmati, passaggi sicuri, compliance.",
    audience_4_title: "Tutti gli altri",
    audience_4_text: "Messaggi privati che si aprono più tardi.",
    security_title: "Sicurezza senza hype",
    security_subtitle: "Creato per la prova, non per promesse.",
    security_block1_title: "Creato per la prova, non per promesse",
    security_block1_html: "<p>TrueLock non è solo cifratura: è progettato per aiutare a provare integrità, origine e immutabilità.</p><ul><li>Quando è stato creato</li><li>Che non è stato modificato</li><li>Che ha seguito le regole definite</li></ul><p class=\"micro\">Niente account. Niente server. Nessuna fiducia richiesta.</p>",
    security_block2_title: "Crittografia moderna basata su standard",
    security_block2_html: "<ul><li>AES-256-GCM — cifratura autenticata</li><li>PBKDF2 — derivazione chiavi da password</li><li>SHA-256 / SHA-512 — hashing e integrità</li><li>Nonce e salt casuali sicuri</li><li>Header autenticati contro manomissione</li></ul><p class=\"micro\">Se cambia un byte, la verifica dovrebbe fallire.</p>",
    security_block3_title: "Protezione hardware (quando disponibile)",
    security_block3_html: "<p>Su piattaforme supportate, TrueLock può usare protezione hardware.</p><ul><li>Secure Enclave su iOS</li><li>TPM / moduli di sicurezza di sistema su desktop</li><li>Secure storage su Android</li></ul><ul><li>Le chiavi non vengono loggate</li><li>Non hardcoded</li><li>Rimosse dalla memoria quando possibile</li></ul>",
    security_block4_title: "Integrità verificabile — nel tempo",
    security_block4_html: "<p>Le capsule sono verificabili offline — ora o più tardi.</p><ul><li>Nessuna dipendenza dal cloud</li><li>Nessun server di cui fidarsi</li><li>Nessun account richiesto</li></ul><p class=\"micro\">La verifica è sempre gratuita.</p>",
    security_block5_title: "Resistenza a manomissione e replay",
    security_block5_html: "<ul><li>Manomissione → rilevata da cifratura autenticata</li><li>Replay → ridotti con nonces unici</li><li>Attacchi di timing → mitigati quando possibile</li><li>Estrazione parziale → rompe la verifica</li></ul><p class=\"micro\">Se qualcuno tenta di falsificare o re‑impacchettare, la verifica dovrebbe fallire.</p>",
    security_block6_title: "Privacy by design",
    security_block6_html: "<ul><li>Nessun tracking</li><li>Nessun SDK di analytics nelle capsule</li><li>Nessuna iniezione nascosta di metadati</li><li>Nessun logging server del contenuto</li></ul><p class=\"micro\">Ciò che blocchi è noto solo a te e al destinatario.</p>",
    security_block7_title: "Trasparente e auditabile",
    security_block7_html: "<p>Le decisioni di sicurezza sono esplicite e progettate per l’audit. Il formato della capsula e il flusso crittografico sono documentati.</p><p class=\"micro\">La fiducia viene dalla verificabilità, non dal marketing.</p>",
    security_block8_title: "Cosa significa per gli utenti",
    security_block8_html: "<ul><li>Non serve credere a parole</li><li>Non serve fidarsi di un’azienda</li><li>Non serve un account</li></ul><p class=\"micro\">Puoi provare: esisteva, non è cambiato, le regole sono state applicate.</p>",
    security_summary_title: "Riepilogo",
    security_summary_html: "<ul><li>Crittografia moderna</li><li>Verifica offline senza server</li><li>Protezione hardware quando disponibile</li><li>Privacy by design</li><li>Prova sopra le promesse</li></ul>",
    pricing_title: "Prezzi semplici",
    pricing_subtitle: "Aprire e verificare è gratis. Pro per creare.",
    pricing_free_title: "Gratis",
    pricing_free_price: "$0",
    pricing_free_item1: "Apri e verifica qualsiasi capsula",
    pricing_free_item2: "Decifra i file ricevuti",
    pricing_free_item3: "Nessun account richiesto",
    pricing_pro_title: "Pro",
    pricing_pro_price: "$9.99 una tantum • 1 dispositivo",
    pricing_pro_item1: "Crea capsule con blocco per tempo, luogo o password",
    pricing_pro_item2: "Allega file, foto e video",
    pricing_pro_item3: "Combina le regole con AND/OR",
    pricing_pro_item4: "Flussi batch e archivi",
    pricing_pro_note: "Licenza una tantum. Nessun abbonamento.",
    pricing_cta: "Sblocca Pro",
    download_title: "Scarica TrueLock",
    download_text: "Scegli la piattaforma. Funziona offline.",
    download_android: "Scarica per Android",
    download_ios: "Scarica per iOS",
    download_windows: "Scarica per Windows",
    download_macos: "Scarica per macOS",
    download_linux: "Scarica per Linux",
    final_title: "Crea la tua prima capsula in 30 secondi.",
    final_text: "Dimostra cosa sapevi. Apri quando deve aprirsi.",
    final_cta: "Crea una capsula",
    footer_tagline: "Nessun server • Nessun account • Offline-first",
    footer_copy: "© 2026 TrueLock"
  },
  pt: {    meta_title: "TrueLock — Cápsulas de confiança",
    meta_description: "Bloqueie informações por tempo, lugar ou senha. Prove que existiam antes do evento.",
    logo_alt: "Logo TrueLock",
    nav_pain: "Problema",
    nav_breakthrough: "Virada",
    nav_cases: "Casos de uso",
    nav_security: "Segurança",
    nav_pricing: "Preços",
    nav_download: "Baixar",
    cta_primary: "Criar cápsula",
    cta_secondary: "Ver como funciona",
    hero_eyebrow: "Prova antes do evento",
    hero_title: "TrueLock — Cápsulas de confiança para o mundo real",
    hero_subtitle_html: "Bloqueie informações por <strong>tempo</strong>, <strong>lugar</strong> ou <strong>senha</strong>. Prove que existiam antes do evento.",
    hero_note: "Sem contas. Funciona offline. Descriptografar e verificar é grátis.",
    hero_card_1_title: "Criar",
    hero_card_1_desc: "Adicione texto, arquivos, fotos ou vídeo.",
    hero_card_2_title: "Bloquear",
    hero_card_2_desc: "Defina regras: tempo, local, senha, AND/OR.",
    hero_card_3_title: "Compartilhar",
    hero_card_3_desc: "Envie a cápsula para qualquer lugar. Abrir é grátis.",
    pain_title: "A internet está cheia de alegações. Mas não há prova.",
    pain_subtitle: "Todo dia:",
    pain_list_1: "Traders falsificam sinais vencedores",
    pain_list_2: "Tipsters editam previsões após o jogo",
    pain_list_3: "Influenciadores prometem drops exclusivos",
    pain_list_4: "Marketers fazem campanhas \"reais\"",
    pain_list_5: "Jornalistas não conseguem provar quem sabia o quê e quando",
    pain_statement_title: "O mesmo problema em todo lugar: qualquer um pode mudar o passado.",
    pain_statement_text: "Capturas, posts, PDFs, documentos — tudo pode ser editado, apagado ou falsificado.",
    pain_proof_title: "Não há como provar:",
    pain_proof_1: "o que foi escrito",
    pain_proof_2: "quando foi escrito",
    pain_proof_3: "que não foi alterado",    breakthrough_title: "A virada",
    breakthrough_text_html: "E se você pudesse bloquear a informação criptograficamente para que <strong>não abra</strong> e <strong>não possa ser alterada</strong>?",
    breakthrough_list_1: "Crie uma cápsula com texto, arquivos, fotos ou vídeo",
    breakthrough_list_2: "Bloqueio por tempo",
    breakthrough_list_3: "Bloqueio por local",
    breakthrough_list_4: "Bloqueio por senha (AND/OR)",
    breakthrough_note: "Até que as condições sejam cumpridas, o conteúdo fica bloqueado — mas qualquer pessoa pode verificar que ele existe.",
    cases_title: "Três casos principais",
    cases_subtitle: "Cenários reais claros, entendidos em segundos.",
    case1_label: "Caso 1",
    case1_title: "Proof Capsules",
    case1_headline: "Publique previsões com prova.",
    case1_step1: "Crie um sinal de trading",
    case1_step2: "Bloqueie por tempo e senha",
    case1_step3: "Publique a cápsula publicamente",
    case1_step4: "Compartilhe a senha depois",
    case1_note: "Todos veem timestamps, hash e regras.",
    case1_tail: "Quando chegar a hora, qualquer um pode verificar que você estava certo. Sem servidores.",
    case2_label: "Caso 2",
    case2_title: "Event Capsules",
    case2_headline: "Transforme criptografia em eventos reais.",
    case2_example: "Exemplo: abrir um segredo no Portão de Brandemburgo às 12:00–12:30.",
    case2_inside_title: "Pode conter:",
    case2_inside_1: "Prêmio ou código promo",
    case2_inside_2: "Mensagem ou convite",
    case2_inside_3: "QR para acesso",
    case2_inside_4: "Próximo passo de uma quest",
    case2_note: "As pessoas se reúnem. Os telefones abrem só no local.",
    case3_label: "Caso 3",
    case3_title: "Campaign Capsules",
    case3_headline: "Abre por tempo ou senha.",
    case3_text: "Exemplo: um creator bloqueia uma cápsula por tempo E senha. Parceiros têm acesso antecipado; todos verificam depois.",
    case3_example: "TrueLock não cuida da distribuição — você compartilha a senha separadamente.",
    case3_note: "Acesso baseado em confiança, sem servidores.",
    audience_title: "Para quem é?",
    audience_1_title: "Creators",
    audience_1_text: "Drops exclusivos, caça ao tesouro, eventos IRL.",
    audience_2_title: "Traders e tipsters",
    audience_2_text: "Sinais com prova, sem edição posterior.",
    audience_3_title: "Times",
    audience_3_text: "Lançamentos programados, repasses seguros, compliance.",
    audience_4_title: "Todo mundo",
    audience_4_text: "Mensagens privadas que abrem depois.",
    security_title: "Segurança sem hype",
    security_subtitle: "Feito para provas, não promessas.",
    security_block1_title: "Feito para provas, não promessas",
    security_block1_html: "<p>TrueLock não serve apenas para criptografar; ele ajuda a provar integridade, origem e imutabilidade.</p><ul><li>Quando foi criado</li><li>Que não foi modificado</li><li>Que seguiu as regras definidas</li></ul><p class=\"micro\">Sem contas. Sem servidores. Sem confiança exigida.</p>",
    security_block2_title: "Criptografia moderna baseada em padrões",
    security_block2_html: "<ul><li>AES-256-GCM — criptografia autenticada</li><li>PBKDF2 — derivação de chaves de senha</li><li>SHA-256 / SHA-512 — hashing e integridade</li><li>Nonces e salts aleatórios seguros</li><li>Headers autenticados contra manipulação</li></ul><p class=\"micro\">Se um byte mudar, a verificação deve falhar.</p>",
    security_block3_title: "Proteção com hardware (quando disponível)",
    security_block3_html: "<p>Em plataformas compatíveis, TrueLock pode usar proteção com hardware.</p><ul><li>Secure Enclave no iOS</li><li>TPM / módulos de segurança do sistema no desktop</li><li>Secure storage no Android</li></ul><ul><li>As chaves não são logadas</li><li>Não hardcoded</li><li>Removidas da memória quando possível</li></ul>",
    security_block4_title: "Integridade verificável — ao longo do tempo",
    security_block4_html: "<p>As cápsulas podem ser verificadas offline — agora ou depois.</p><ul><li>Sem dependência de nuvem</li><li>Sem servidor em que confiar</li><li>Sem conta exigida</li></ul><p class=\"micro\">A verificação é sempre gratuita.</p>",
    security_block5_title: "Resistência a manipulação e replay",
    security_block5_html: "<ul><li>Manipulação → detectada por criptografia autenticada</li><li>Ataques replay → reduzidos por nonces únicos</li><li>Ataques de timing → mitigados quando possível</li><li>Extração parcial → quebra a verificação</li></ul><p class=\"micro\">Se alguém tentar falsificar ou re‑embalar uma cápsula, a verificação deve falhar.</p>",
    security_block6_title: "Privacidade por design",
    security_block6_html: "<ul><li>Sem tracking</li><li>Sem SDKs de analytics nas cápsulas</li><li>Sem injeção oculta de metadados</li><li>Sem logging servidor do conteúdo</li></ul><p class=\"micro\">O que você bloqueia é conhecido apenas por você e o destinatário.</p>",
    security_block7_title: "Transparente e auditável",
    security_block7_html: "<p>As decisões de segurança são explícitas e pensadas para auditoria. O formato da cápsula e o fluxo criptográfico são documentados.</p><p class=\"micro\">A confiança vem da verificação, não do marketing.</p>",
    security_block8_title: "O que isso significa para os usuários",
    security_block8_html: "<ul><li>Você não precisa acreditar em nada</li><li>Você não precisa confiar em uma empresa</li><li>Você não precisa de conta</li></ul><p class=\"micro\">Você pode provar: existia, não mudou, as regras foram aplicadas.</p>",
    security_summary_title: "Resumo",
    security_summary_html: "<ul><li>Criptografia moderna</li><li>Verificação offline sem servidores</li><li>Proteção com hardware quando disponível</li><li>Privacidade por design</li><li>Prova acima de promessas</li></ul>",
    pricing_title: "Preços simples",
    pricing_subtitle: "Abrir e verificar é grátis. Pro para criar.",
    pricing_free_title: "Grátis",
    pricing_free_price: "$0",
    pricing_free_item1: "Abrir e verificar qualquer cápsula",
    pricing_free_item2: "Descriptografar arquivos recebidos",
    pricing_free_item3: "Sem conta",
    pricing_pro_title: "Pro",
    pricing_pro_price: "$9.99 pagamento único • 1 dispositivo",
    pricing_pro_item1: "Criar cápsulas com bloqueio por tempo, local ou senha",
    pricing_pro_item2: "Anexar arquivos, fotos e vídeo",
    pricing_pro_item3: "Combinar regras com AND/OR",
    pricing_pro_item4: "Fluxos em lote e arquivos",
    pricing_pro_note: "Licença única. Sem assinatura.",
    pricing_cta: "Desbloquear Pro",
    download_title: "Baixar TrueLock",
    download_text: "Escolha sua plataforma. Funciona offline.",
    download_android: "Baixar para Android",
    download_ios: "Baixar para iOS",
    download_windows: "Baixar para Windows",
    download_macos: "Baixar para macOS",
    download_linux: "Baixar para Linux",
    final_title: "Crie sua primeira cápsula em 30 segundos.",
    final_text: "Prove o que você sabia. Abra quando for a hora.",
    final_cta: "Criar cápsula",
    footer_tagline: "Sem servidores • Sem contas • Offline-first",
    footer_copy: "© 2026 TrueLock"
  },
  tr: {    meta_title: "TrueLock — Güven Kapsülleri",
    meta_description: "Bilgiyi zaman, yer veya parola ile kilitle. Olaydan önce var olduğunu kanıtla.",
    logo_alt: "TrueLock logosu",
    nav_pain: "Sorun",
    nav_breakthrough: "Atılım",
    nav_cases: "Kullanım alanları",
    nav_security: "Güvenlik",
    nav_pricing: "Fiyat",
    nav_download: "İndir",
    cta_primary: "Kapsül oluştur",
    cta_secondary: "Nasıl çalışır",
    hero_eyebrow: "Olaydan önce kanıt",
    hero_title: "TrueLock — Gerçek dünya için güven kapsülleri",
    hero_subtitle_html: "Bilgiyi <strong>zaman</strong>, <strong>yer</strong> veya <strong>parola</strong> ile kilitle. Olaydan önce var olduğunu kanıtla.",
    hero_note: "Hesap yok. Offline çalışır. Çözme ve doğrulama ücretsiz.",
    hero_card_1_title: "Oluştur",
    hero_card_1_desc: "Metin, dosya, fotoğraf veya video ekle.",
    hero_card_2_title: "Kilitle",
    hero_card_2_desc: "Kurallar: zaman, konum, parola, AND/OR.",
    hero_card_3_title: "Paylaş",
    hero_card_3_desc: "Kapsülü her yere gönder. Ücretsiz açılır.",
    pain_title: "İnternet iddialarla dolu. Ama kanıt yok.",
    pain_subtitle: "Her gün:",
    pain_list_1: "Trader'lar kazanç sinyallerini sahteleyebilir",
    pain_list_2: "Tipster'lar maçtan sonra tahminleri düzenler",
    pain_list_3: "Influencer'lar \"özel\" drop'lar vaat eder",
    pain_list_4: "Pazarlamacılar \"gerçek\" kampanyalar yapar",
    pain_list_5: "Gazeteciler kimin neyi ne zaman bildiğini kanıtlayamaz",
    pain_statement_title: "Aynı sorun her yerde: herkes geçmişi değiştirebilir.",
    pain_statement_text: "Ekran görüntüleri, postlar, PDF'ler, belgeler — hepsi düzenlenebilir, silinebilir veya sahte olabilir.",
    pain_proof_title: "Kanıtlamak zor:",
    pain_proof_1: "ne yazıldığını",
    pain_proof_2: "ne zaman yazıldığını",
    pain_proof_3: "değiştirilmediğini",    breakthrough_title: "Atılım",
    breakthrough_text_html: "Bilgiyi kriptografik olarak kilitleyip <strong>açılamamasını</strong> ve <strong>değiştirilememesini</strong> sağlasan?",
    breakthrough_list_1: "Metin, dosya, fotoğraf veya video ile kapsül oluştur",
    breakthrough_list_2: "Zamana göre kilitle",
    breakthrough_list_3: "Konuma göre kilitle",
    breakthrough_list_4: "Parola ile kilitle (AND/OR birleştir)",
    breakthrough_note: "Koşullar sağlanana kadar içerik kilitli kalır — ama herkes var olduğunu doğrulayabilir.",
    cases_title: "Üç ana kullanım",
    cases_subtitle: "Kullanıcıların saniyeler içinde anladığı gerçek senaryolar.",
    case1_label: "Kullanım 1",
    case1_title: "Proof Capsules",
    case1_headline: "Kanıtla birlikte tahmin yayınla.",
    case1_step1: "Bir trading sinyali oluştur",
    case1_step2: "Zaman ve parola ile kilitle",
    case1_step3: "Kapsülü herkese açık yayınla",
    case1_step4: "Parolayı sonra paylaş",
    case1_note: "Herkes zaman damgasını, hash'i ve kuralları görür.",
    case1_tail: "Zaman gelince herkes doğrulayabilir. Sunucu yok.",
    case2_label: "Kullanım 2",
    case2_title: "Event Capsules",
    case2_headline: "Şifrelemeyi gerçek etkinliklere dönüştür.",
    case2_example: "Örnek: Brandenburg Kapısı'nda 12:00–12:30 arasında bir sır aç.",
    case2_inside_title: "İçinde olabilir:",
    case2_inside_1: "Ödül veya promo kod",
    case2_inside_2: "Mesaj veya davet",
    case2_inside_3: "Erişim için QR",
    case2_inside_4: "Bir quest'in sonraki adımı",
    case2_note: "İnsanlar toplanır. Telefonlar sadece yerde açılır.",
    case3_label: "Kullanım 3",
    case3_title: "Campaign Capsules",
    case3_headline: "Zaman veya parola ile açılır.",
    case3_text: "Örnek: Bir creator kapsülü zaman VE parola ile kilitler. Partnerler erken erişir; herkes sonra doğrular.",
    case3_example: "TrueLock dağıtımı yönetmez — parolayı ayrı paylaşırsın.",
    case3_note: "Sunucusuz, güvene dayalı erişim.",
    audience_title: "Kimler için?",
    audience_1_title: "Creator'lar",
    audience_1_text: "Özel drop'lar, hazine avları, IRL etkinlikler.",
    audience_2_title: "Trader'lar ve tipster'lar",
    audience_2_text: "Kanıtlı sinyaller, sonradan düzenleme yok.",
    audience_3_title: "Ekipler",
    audience_3_text: "Zamanlı yayınlar, güvenli teslimler, uyumluluk.",
    audience_4_title: "Diğer herkes",
    audience_4_text: "Sonradan açılan özel mesajlar.",
    security_title: "Hypesız güvenlik",
    security_subtitle: "Kanıt için tasarlandı, söz için değil.",
    security_block1_title: "Kanıt için tasarlandı, söz için değil",
    security_block1_html: "<p>TrueLock yalnızca şifreleme için değil, bütünlük, köken ve değişmezliği kanıtlamaya yardımcı olmak için tasarlandı.</p><ul><li>Ne zaman oluşturulduğu</li><li>Değiştirilmediği</li><li>Belirlediğin kurallara uyduğu</li></ul><p class=\"micro\">Hesap yok. Sunucu yok. Güven gerekmez.</p>",
    security_block2_title: "Modern, standartlara dayalı kriptografi",
    security_block2_html: "<ul><li>AES-256-GCM — kimlik doğrulamalı şifreleme</li><li>PBKDF2 — paroladan anahtar türetme</li><li>SHA-256 / SHA-512 — hashing ve bütünlük</li><li>Güvenli rastgele nonce ve salt</li><li>Manipülasyonu azaltan doğrulanmış başlıklar</li></ul><p class=\"micro\">Bir bayt değişirse doğrulamanın başarısız olması beklenir.</p>",
    security_block3_title: "Donanım destekli koruma (mevcutsa)",
    security_block3_html: "<p>Desteklenen platformlarda TrueLock donanım destekli koruma kullanabilir.</p><ul><li>iOS’ta Secure Enclave</li><li>Desktop’ta TPM / sistem güvenlik modülleri</li><li>Android’de Secure storage</li></ul><ul><li>Anahtarlar loglanmaz</li><li>Hardcode edilmez</li><li>Mümkün olduğunda bellekten temizlenir</li></ul>",
    security_block4_title: "Doğrulanabilir bütünlük — zaman içinde",
    security_block4_html: "<p>Kapsüller offline doğrulanabilir — şimdi veya daha sonra.</p><ul><li>Bulut bağımlılığı yok</li><li>Güvenilecek sunucu yok</li><li>Hesap gerekmez</li></ul><p class=\"micro\">Doğrulama her zaman ücretsizdir.</p>",
    security_block5_title: "Manipülasyon ve replay direnci",
    security_block5_html: "<ul><li>Manipülasyon → kimlik doğrulamalı şifreleme ile tespit edilir</li><li>Replay saldırıları → benzersiz nonce’larla azaltılır</li><li>Zamanlama saldırıları → mümkün olduğunda azaltılır</li><li>Kısmi çıkarım → doğrulamayı bozar</li></ul><p class=\"micro\">Bir kapsül sahtelemeye çalışılırsa doğrulama başarısız olmalıdır.</p>",
    security_block6_title: "Gizlilik tasarım gereği",
    security_block6_html: "<ul><li>Takip yok</li><li>Kapsüller içinde analytics SDK yok</li><li>Gizli metadata enjeksiyonu yok</li><li>İçerik için sunucu logları yok</li></ul><p class=\"micro\">Kilitlediğin içerik sadece sen ve alıcı tarafından bilinir.</p>",
    security_block7_title: "Şeffaf ve denetlenebilir",
    security_block7_html: "<p>Güvenlik kararları açık ve denetime uygun şekilde tasarlanmıştır. Kapsül formatı ve kripto akışı belgelenmiştir.</p><p class=\"micro\">Güven, pazarlamadan değil, doğrulanabilirlikten gelir.</p>",
    security_block8_title: "Kullanıcılar için ne anlama gelir",
    security_block8_html: "<ul><li>İnanmak zorunda değilsin</li><li>Şirkete güvenmek zorunda değilsin</li><li>Hesap gerekmez</li></ul><p class=\"micro\">Kanıtlayabilirsin: var oldu, değişmedi, kurallar uygulandı.</p>",
    security_summary_title: "Özet",
    security_summary_html: "<ul><li>Modern kriptografi</li><li>Offline, sunucusuz doğrulama</li><li>Mevcutsa donanım destekli koruma</li><li>Gizlilik odaklı tasarım</li><li>Vaad değil, kanıt</li></ul>",
    pricing_title: "Basit fiyatlandırma",
    pricing_subtitle: "Açma ve doğrulama ücretsiz. Oluşturma için Pro.",
    pricing_free_title: "Ücretsiz",
    pricing_free_price: "$0",
    pricing_free_item1: "Her kapsülü aç ve doğrula",
    pricing_free_item2: "Aldığın dosyaları çöz",
    pricing_free_item3: "Hesap gerekmez",
    pricing_pro_title: "Pro",
    pricing_pro_price: "$9.99 tek seferlik • 1 cihaz",
    pricing_pro_item1: "Zaman, yer veya parola kilidiyle kapsül oluştur",
    pricing_pro_item2: "Dosya, fotoğraf ve video ekle",
    pricing_pro_item3: "Kuralları AND/OR ile birleştir",
    pricing_pro_item4: "Toplu ve arşiv iş akışları",
    pricing_pro_note: "Tek seferlik lisans. Abonelik yok.",
    pricing_cta: "Pro'yu aç",
    download_title: "TrueLock indir",
    download_text: "Platformunu seç. Offline çalışır.",
    download_android: "Android için indir",
    download_ios: "iOS için indir",
    download_windows: "Windows için indir",
    download_macos: "macOS için indir",
    download_linux: "Linux için indir",
    final_title: "İlk kapsülünü 30 saniyede oluştur.",
    final_text: "Ne bildiğini kanıtla. Zamanı geldiğinde aç.",
    final_cta: "Kapsül oluştur",
    footer_tagline: "Sunucu yok • Hesap yok • Offline-first",
    footer_copy: "© 2026 TrueLock"
  }
};

Object.keys(landingOverrides).forEach((lang) => {
  if (typeof translations === "undefined") {
    return;
  }
  translations[lang] = {
    ...(translations[lang] || {}),
    ...landingOverrides[lang],
  };
});